language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages: &precise_latest_boost_packages
            - gcc-6
            - g++-6
          sources: &precise_latest_boost_sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
      #env:
      #  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}



install:
#Installing Boost 1.65
- BOOST_VERSION=1.65.0
- |
  sudo wget -O boost_1_65_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.65.0/boost_1_65_0.tar.gz/download
  sudo tar xzvf boost_1_65_0.tar.gz
  cd boost_1_65_0/
  sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=filesystem,system
  sudo ./b2 link=shared threading=multi variant=release
  sudo ./b2 install

  #Installing cmake 3.9.6
  - CMAKE_VERSION=3.9.6
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  - cmake --version
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v



script:
  - cd controller/CAPTAIN
  - cmake CMakeLists.txt
  - make
